const legacyQuestions = [
  ['Ikinyabiziga cyose cyangwa ibinyabiziga bigenda bigomba kugira:', ['Umuyobozi','Umuherekeza','A na B ni ibisubizo by’ukuri','Nta gisubizo cy’ukuri kirimo'], 0],
  ['Ijambo “akayira” bivuga inzira nyabagendwa ifunganye yagenewe gusa:', ['Abanyamaguru','Ibinyabiziga bigendera ku biziga bibiri','A na B ni ibisubizo by’ukuri','Nta gisubizo cy’ukuri kirimo'], 2],
  ['Umurongo uciyemo uduce umenyesha ahegereye umurongo ushobora kuzuzwa n’uturanga gukata tw’ibara ryera utwo turanga cyerekezo tumenyesha:', ['Igisate cy’umuhanda abayobozi bagomba gukurikira','Ahegereye umurongo ukomeje','Igabanurwa ry’umubare w’ibisate by’umuhanda mu cyerekezo bajyamo','A na C nibyo'], 2],
  ['Ahantu ho kugendera mu muhanda herekanwa n’ibimenyetso bimurika ibinyabiziga ntibishobora kuhagenda:', ['Biteganye','Ku murongo umwe','A na B nibyo','Nta gisubizo cy’ukuri kirimo'], 3],
  ['Ibinyabiziga bikurikira bigomba gukorerwa isuzumwa buri mwaka:', ['Ibinyabiziga bigenewe gutwara abagenzi muri rusange','Ibinyabiziga bigenewe gutwara ibintu birengeje toni 3.5','Ibinyabiziga bigenewe kwigisha gutwara','Nta gisubizo cy’ukuri kirimo'], 3],
  ['Ubugari bwa romoruki ikuruwe n’ikinyamitende itatu ntibugomba kurenza:', ['cm 75','cm 125','cm 265','Nta gisubizo cy’ukuri'], 3],
  ['Uburebure bw’ibinyabiziga bikurikira ntibugomba kurenga metero 11:', ['Ibifite umutambiko umwe uhuza imipira','Ibifite imitambiko ibiri ikurikiranye mu bugari bwayo','Makuzungu','Nta gisubizo cy’ukuri'], 3],
  ['Ikinyabiziga kibujijwe guhagarara akanya kanini aha hakurikira:', ['Ahatarengeje metero 1 imbere cyangwa inyuma y’ikinyabiziga gihagaze','Ahantu hari ibimenyetso bibuza byabugenewe','Aho abanyamaguru banyura mu muhanda bakikire inkomyi','Ibisubizo byose nibyo'], 3],
  ['Kunyuranaho bikorerwa:', ['Mu ruhande rw’iburyo gusa','Igihe cyose ni ibumoso','Iburyo iyo unyura ku nyamaswa','Nta gisubizo cy’ukuri kirimo'], 3],
  ['Icyapa cyerekana umuvuduko ntarengwa gishyirwa gusa ku binyabiziga bifite uburemere:', ['Burenga toni 1','Burenga toni 2','Burenga toni 24','Nta gisubizo cy’ukuri kirimo'], 3],
  ['Ahatari mu nsisiro umuvuduko ntarengwa wa velomoteri ni:', ['Km 50','Km 40','Km 30','Nta gisubizo cy’ukuri'], 0],
  ['Umuyobozi ashobora kunyura mu kayira k’abanyamaguru amaze kureba ibi bikurikira:', ['Umuvuduko w’abanyamaguru','Ubugari bw’umuhanda','Umubare w’abanyamaguru','Nta gisubizo cy’ukuri kirimo'], 3],
  ['Birabujijwe gukoresha andi matara uretse ategetswe, ariko ntibireba:', ['Amatara ndanga','Amatara ari imbere mu modoka','Amatara ndangaburambarare','Ibisubizo byose nibyo'], 1],
  ['Iyo nta mategeko awugabanya by’umwihariko, umuvuduko ntarengwa w’amapikipiki ni:', ['Km 25','Km 70','Km 40','Nta gisubizo cy’ukuri kirimo'], 3],
  ['Uburyo bukoreshwa kugirango ikinyabiziga kigende gahoro igihe feri idakora neza bwitwa:', ['Feri y’urugendo','Feri yo guhagarara umwanya munini','Feri yo gutabara','Nta gisubizo cy’ukuri kirimo'], 2],
  ['Nibura ikinyabiziga gitegetswe kugira uduhanagurakirahure tungahe?', ['2','3','1','Nta gisubizo cy’ukuri kirimo'], 2],
  ['Amatara maremare y’ikinyabiziga agomba kuzimwa:', ['Iyo umuhanda umurikiye umuyobozi abasha kureba muri metero 20','Iyo ikinyabiziga kigiye kubisikana n’ibindi','Iyo ari mu nsisiro','Ibisubizo byose ni ukuri'], 1],
  ['Ikinyabiziga ntigishobora kugira amatara arenga abiri y’ubwoko bumwe keretse:', ['Itara ndangamubyimba','Itara ryerekana icyerekezo','Itara ndangaburumbarare','Ibisubizo byose ni ukuri'], 3],
  ['Ubugari bwa romoruki ikuruwe n’igare cyangwa velomoteri ntiburenza:', ['cm 25','cm 125','cm 45','Nta gisubizo cy’ukuri kirimo'], 3],
  ['Ibinyabiziga bikoreshwa nka tagisi bishobora gushyirwaho itara ryerekana ko bitakodeshejwe:', ['Itara ry’icyatsi rishyirwa imbere','Itara ry’icyatsi rishyirwa ibumoso','Itara ry’umuhondo rishyirwa inyuma','A na C ni ibisubizo by’ukuri'], 0],
  ['Za otobisi zagenewe gutwara abanyeshuri zishobora gushyirwaho amatara abiri asa n’icunga:', ['Amatara abiri ashyirwa inyuma','Amatara abiri ashyirwa imbere','Rimwe rishyirwa imbere irindi inyuma','B na C ni ibisubizo by’ukuri'], 2],
  ['Itara ryo guhagarara ry’ibara ritukura rigomba kugaragara igihe ijuru rikeye nibura:', ['Metero 100 ku manywa na metero 20 mu ijoro','Metero 150 ku manywa na metero 50 mu ijoro','Metero 200 ku manywa na metero 100 mu ijoro','Nta gisubizo cy’ukuri kirimo'], 3],
  ['Ibikoresho by’ihoni bigomba kumvikana mu ntera iyo umuvuduko ushobora kurenga km 50:', ['Metero 100','Metero 200','Metero 50','Metero 150'], 2],
  ['Igice cy’inzira nyabagendwa gicagaguye gifite ubugari budahagije kugira ngo imodoka zitambuke neza kiba:', ['Aha nyurwa n’amagare na velomoteri','Aha nyurwa n’ingorofani','Aha nyurwa n’ibinyamitende','Nta gisubizo cy’ukuri'], 2],
  ['Ubugari bwa romoruki ntiburenza ubugari bw’ikinyabiziga kiyikurura iyo ikuruwe n:', ['Igare','Velomoteri','Ipikipiki ifite akanyabiziga kometse ku ruhande','Nta gisubizo cy’ukuri'], 2],
  ['Abana badafite imyaka ingahe ntibatwarwa ku ntebe y’imbere iyo nta handi hantu?', ['Imyaka 10','Imyaka 12','Imyaka 7','Nta gisubizo cy’ukuri'], 1],
  ['Icyapa kivuga gutambuka mbere y’ibinyabiziga biturutse imbere gifite:', ['Ubuso bw’umweru','Ikirango cy’umutuku n’umukara','Ikirango cy’umweru n’umukara','Nta gisubizo cy’ukuri'], 3],
  ['Itegeko rigenga gutambuka mbere kw’iburyo rikurikizwa mu masangano:', ['Iyo nta cyapa cyo gutambuka mbere gihari','Iyo ikimenyetso kimurika cyagenewe ibinyabiziga kidakora','A na B ni ibisubizo by’ukuri','Nta gisubizo cy’ukuri'], 2],
  ['Ibimenyetso bimurika bishyirwa iburyo bw’umuhanda, ariko bishobora no gushyirwa ibumoso cyangwa hejuru:', ['Hakurikijwe icyerekezo abagenzi bireba baganamo','Hakurikijwe icyo ibyo bimenyetso bigamije kwerekana','Kugirango birusheho kugaragara neza','Ibisubizo byose ni ukuri'], 2],
  ['Iyo itara ry’umuhondo rimyatsa rikoreshwe mu masangano rishyirwa:', ['Kuri buri nzira','Hagati y’amasangano','Iburyo bw’amasangano','A na B ni ibisubizo by’ukuri'], 3],
  ['Ibinyabiziga bikurikira bigomba gukorerwa isuzumwa rimwe mu mezi 6:', ['Ibinyabiziga bitwara abagenzi muri rusange','Ibinyabiziga bitwara ibintu birengeje toni 3.5','Ibinyabiziga bigenewe kwigisha gutwara','Ibisubizo byose ni ukuri'], 3],
  ['Iyo kuyobya umuhanda ari ngombwa bigaragazwa n’icyapa gifite ubuso bw’amabara:', ['Ubururu','Umweru','Umutuku','Nta gisubizo cy’ukuri'], 0],
  ['Ku mihanda ibyapa bikurikira bigomba kugaragazwa ku buryo bumwe:', ['Ibyapa biyobora n’ibitegeka','Ibyapa biburira n’ibitegeka','Ibyapa bibuza n’ibitegeka','Nta gisubizo cy’ukuri kirimo'], 2],
  ['Ni iyihe feri ituma imodoka igenda buhoro kandi igahagarara neza uko yaba yikoreye kose?', ['Feri y’urugendo','Feri yo gutabara','Feri yo guhagarara umwanya munini','Nta gisubizo cy’ukuri kirimo'], 0],
  ['Ibizirikisho by’iminyururu bikoreshwa gusa igihe nta kundi byagenda kandi nturenze:', ['Km 20 mu isaha','Km 30 mu isaha','Km 40 mu isaha','Km 50 mu isaha'], 0],
  ['Uburemere ntarengwa ku binyabiziga bifite imitambiko itatu cyangwa irenga ni:', ['Toni 10','Toni 12','Toni 16','Toni 24'], 2]
].map((item, index) => ({ id: index + 1, question: item[0], options: item[1], answer: item[2] }));

legacyQuestions.push(
  { id: 229, question: 'Iki cyapa kivuga iki?', options: ['Umuvuduko ntarengwa 30 km/h', 'Iherezo ry’umuvuduko muke ntarengwa utegetswe', 'Umuvuduko uri hejuru ya 30 km/h', 'Nta gisubizo cy’ukuri'], answer: 1, image: 'assets/signs/q229-1.jpg', optionImages: ['assets/signs/q229-1.jpg', 'assets/signs/q229-2.jpg', 'assets/signs/q229-3.png'] },
  { id: 230, question: 'Icyapa gikurikira kivuze iki?', options: ['Ntihanyurwa', 'Birabujijwe guhagarara umwanya munini', 'Umuvuduko utarengeje', 'Inzira y’abanyeshuri'], answer: 1, image: 'assets/signs/q230-1.png', optionImages: ['assets/signs/q230-1.png', 'assets/signs/q230-2.png'] },
  { id: 234, question: 'Iki cyapa gisobanura iki?', options: ['Iherezo ry’ibibuzwa byose mu karere ku binyabiziga bigenda', 'Ntihemerewe kuhahagarara', 'Umuvuduko ntarengwa wemewe', 'Nta gisubizo cy’ukuri kirimo'], answer: 0, image: 'assets/signs/q234-1.jpg' },
  { id: 235, question: 'Ibyapa bitegeka bikozwe mu yihe shusho?', options: ['a', 'b', 'c', 'd'], answer: 2, optionImages: ['assets/signs/q235-1.png', 'assets/signs/q235-2.png', 'assets/signs/q235-3.png', 'assets/signs/q235-4.png'] }
);

const allQuestions = window.pdfQuestions || legacyQuestions;
const sourceQuestions = allQuestions.filter((question) => !(question.images?.length || question.image || question.optionImages?.length));
const categoryDefinitions = [
  { key: 'signs', icon: '🚦', title: 'Ibimenyetso byo mu muhanda', description: 'Ibyapa, ibimenyetso bimurika, amabara n’icyo buri kimenyetso gisobanuye.', words: ['icyapa', 'ibyapa', 'ikimenyetso', 'ibimenyetso', 'amatara bimurika'] },
  { key: 'speed', icon: '◷', title: 'Umuvuduko n’umutekano', description: 'Imipaka y’umuvuduko ku binyabiziga bitandukanye, mu nsisiro no hanze yazo.', words: ['umuvuduko', 'km ', 'kilometero', 'umuvuduko muke', 'umuvuduko ntarengwa'] },
  { key: 'passing', icon: '↔', title: 'Gutambuka no kunyuranaho', description: 'Gutambuka mbere, amasangano, kunyuranaho n’amategeko yo guhindura icyerekezo.', words: ['kunyuranaho', 'gutambuka', 'amasangano', 'gutambuka mbere', 'gukatira', 'icyerekezo'] },
  { key: 'vehicles', icon: '◉', title: 'Ibinyabiziga n’ibikoresho', description: 'Feri, amatara, romoruki, amapikipiki n’ibisabwa ku kinyabiziga.', words: ['ikinyabiziga', 'ibinyabiziga', 'romoruki', 'feri', 'amatara', 'ipikipiki', 'velomoteri', 'igare'] },
  { key: 'road', icon: '▧', title: 'Umuhanda n’imirongo', description: 'Imihanda, ibisate, imirongo, inzira z’abanyamaguru n’ahanyurwa.', words: ['umuhanda', 'umurongo', 'igisate', 'akayira', 'inzira nyabagendwa', 'abanyamaguru'] },
  { key: 'documents', icon: '▤', title: 'Inyandiko n’isuzumwa', description: 'Uruhushya, ibyangombwa, ubwishingizi, kwandikisha no gusuzuma ibinyabiziga.', words: ['uruhushya', 'icyangombwa', 'isuzumwa', 'ubwishingizi', 'iyandikwa', 'ikarita'] },
  { key: 'safety', icon: '✚', title: 'Umutekano n’impanuka', description: 'Impanuka, telefoni, ihoni, gutabara n’imyitwarire irinda abandi.', words: ['impanuka', 'inkomere', 'umutekano', 'telephone', 'ihoni', 'gutabara', 'ibyago'] },
  { key: 'other', icon: '＋', title: 'Ibindi bibazo', description: 'Ibibazo bitajyanye n’andi matsinda, kugira ngo nta kibazo gisigara hanze.', words: [] }
];
const questionText = (question) => [question.question, ...question.options].join(' ').toLocaleLowerCase();
const topicSets = Object.fromEntries(categoryDefinitions.map((category) => [category.key, sourceQuestions.filter((question) => category.words.length === 0 || category.words.some((word) => questionText(question).includes(word))).map((question) => question.id)]));
const matchedQuestionIds = new Set(categoryDefinitions.filter((category) => category.key !== 'other').flatMap((category) => topicSets[category.key]));
topicSets.other = sourceQuestions.filter((question) => !matchedQuestionIds.has(question.id)).map((question) => question.id);
const state = { view: 'home', quiz: [], quizSize: 0, quizTitle: 'IKIZAMINI GISHYA', current: 0, selected: null, answered: false, score: 0, missed: [], categoryPool: null, categoryKey: null, categoryOffset: 0, attempts: Number(localStorage.getItem('umuhandaAttempts') || 0), best: Number(localStorage.getItem('umuhandaBest') || 0) };
const app = document.querySelector('#app');
const shuffle = (items) => [...items].sort(() => Math.random() - 0.5);
const escapeHtml = (value) => value.replace(/[&<>'"]/g, (char) => ({ '&':'&amp;', '<':'&lt;', '>':'&gt;', "'":'&#039;', '"':'&quot;' }[char]));
function resetQuiz(questions, title = 'IKIZAMINI GISHYA') { state.quiz = questions.map((item) => { const completeImageChoices = item.optionImages?.length === 4; const questionImages = [...(item.images || []), ...(item.image ? [item.image] : []), ...(!completeImageChoices ? (item.optionImages || []) : [])]; return { ...item, questionImages, options: item.options.map((text, index) => ({ text, image: completeImageChoices ? item.optionImages[index] : undefined, correct: index === item.answer })) }; }); state.quizSize = state.quiz.length; state.quizTitle = title; state.current = 0; state.selected = null; state.answered = false; state.score = 0; state.missed = []; state.tracked = false; state.view = 'quiz'; render(); }
function startQuiz() { state.categoryPool = null; state.categoryKey = null; state.categoryOffset = 0; resetQuiz(shuffle(sourceQuestions)); }
function loadCategoryBatch() { const category = categoryDefinitions.find((item) => item.key === state.categoryKey); const batch = state.categoryPool.slice(state.categoryOffset, state.categoryOffset + 20); resetQuiz(batch, `INGINGO: ${(category?.title || state.categoryKey).toUpperCase()} · ${state.categoryOffset + 1}-${state.categoryOffset + batch.length}`); }
function startCategory(categoryKey) { state.categoryKey = categoryKey; state.categoryPool = shuffle((topicSets[categoryKey] || []).map((id) => sourceQuestions.find((item) => item.id === id)).filter(Boolean)); state.categoryOffset = 0; loadCategoryBatch(); }
function startTopic(topic) { startCategory(topic); }
function nextCategoryBatch() { if (!state.categoryPool || state.categoryOffset + state.quizSize >= state.categoryPool.length) return; state.categoryOffset += state.quizSize; loadCategoryBatch(); }
function retryQuiz() { state.quiz = shuffle(state.quiz); state.current = 0; state.selected = null; state.answered = false; state.score = 0; state.missed = []; state.tracked = false; state.view = 'quiz'; render(); }
function renderHome() { return `<div class="hero"><div><div class="eyebrow">Umunsi umwe usigaye</div><h1>Menya amategeko.<br><em>Witegure gutsinda.</em></h1><p>Kwitoza ku bibazo byose bishingiye ku nyandiko y’amategeko y’umuhanda. Ikizamini kirimo ibibazo ${sourceQuestions.length} kandi buri kibazo kigumana inyandiko n’amashusho byacyo.</p></div><button class="primary" onclick="startQuiz()">Tangira ikizamini <span>→</span></button></div><div class="stats"><div class="stat"><div><h3>${state.attempts}</h3><p>Ibizamini wakoze</p></div><div class="stat-icon">✓</div></div><div class="stat"><div><h3>${state.best ? `${state.best}%` : '—'}</h3><p>Amanota meza</p></div><div class="stat-icon">↗</div></div><div class="stat"><div><h3>${sourceQuestions.length}</h3><p>Ibibazo byose</p></div><div class="stat-icon">◌</div></div></div><div class="section-head"><h2>Ingingo z’ingenzi</h2><a class="text-link" href="#topics">Zose →</a></div><div class="topic-grid"><div class="topic"><div class="topic-icon">🚦</div><h3>Ibimenyetso</h3><p>Menya ibisobanuro by’ibimenyetso byo mu muhanda.</p></div><div class="topic"><div class="topic-icon">◷</div><h3>Umuvuduko</h3><p>Witoze imipaka y’umuvuduko n’amategeko yayo.</p></div><div class="topic"><div class="topic-icon">↔</div><h3>Gutambuka</h3><p>Gusobanukirwa kunyuranaho no gutambuka mbere.</p></div></div>`; }
function renderQuiz() { if (state.current >= state.quiz.length) return renderResults(); const q = state.quiz[state.current]; const percent = ((state.current) / state.quizSize) * 100; const questionImages = (q.questionImages || []).map((image, index) => `<img class="question-image" src="${image}" alt="Ishusho ${index + 1} ijyanye n’ikibazo" />`).join(''); const imageAnswers = q.options.every((option) => option.image); return `<div class="quiz-wrap"><div class="quiz-header"><strong>${state.quizTitle}</strong><span style="color:var(--muted);font-size:12px">${state.current + 1} / ${state.quizSize}</span></div><div class="progress"><span style="width:${percent}%"></span></div><div class="question-card"><div class="question-label">Ikibazo ${state.current + 1}</div><h1>${escapeHtml(q.question)}</h1>${questionImages ? `<div class="question-visuals">${questionImages}</div>` : ''}<div class="answers${imageAnswers ? ' image-answers' : ''}">${q.options.map((option, index) => { let result = ''; if (state.answered) result = option.correct ? ' correct' : (state.selected === index ? ' wrong' : ''); const optionImage = option.image ? `<img class="option-image" src="${option.image}" alt="Igisubizo ${String.fromCharCode(65 + index)}" />` : ''; return `<button class="answer${state.selected === index ? ' selected' : ''}${result}" onclick="chooseAnswer(${index})" ${state.answered ? 'disabled' : ''}><span class="letter">${String.fromCharCode(65 + index)}</span>${optionImage}<span>${escapeHtml(option.text)}</span></button>`; }).join('')}</div><div class="quiz-actions">${state.answered ? `<span class="hint">${state.selected !== null && q.options[state.selected].correct ? 'Ni byo! Igisubizo cy’ukuri.' : `Igisubizo cy’ukuri ni ${String.fromCharCode(65 + q.options.findIndex((o) => o.correct))}.`}</span>` : '<span class="hint">Hitamo igisubizo kimwe</span>'}<button class="primary" onclick="${state.answered ? 'nextQuestion()' : 'checkAnswer()'}">${state.answered ? (state.current === state.quizSize - 1 ? 'Reba amanota' : 'Ikibazo gikurikira') : 'Emeza igisubizo'}</button></div></div></div>`; }
function chooseAnswer(index) { if (!state.answered) { state.selected = index; render(); } }
function checkAnswer() { if (state.selected === null) return; state.answered = true; const q = state.quiz[state.current]; if (q.options[state.selected].correct) state.score += 1; else state.missed.push(q); render(); }
function nextQuestion() { state.current += 1; state.selected = null; state.answered = false; render(); }
function renderResults() { const percent = Math.round(state.score / state.quizSize * 100); const passed = percent >= 18; const hasNextBatch = Boolean(state.categoryPool && state.categoryOffset + state.quizSize < state.categoryPool.length); const nextBatchButton = hasNextBatch ? '<button class="primary" onclick="nextCategoryBatch()">Ibibazo 20 bikurikira →</button>' : ''; const batchNote = state.categoryPool ? (hasNextBatch ? `Hari ibibazo ${state.categoryPool.length - state.categoryOffset - state.quizSize} bisigaye muri iri somo.` : 'Warangije ibibazo byose byo muri iri somo.') : ''; return `<div class="eyebrow">Ikizamini kirangiye</div><h1 style="font:700 38px 'Space Grotesk';margin:0 0 25px">${passed ? 'Watsinze! Dore uko wagenze.' : 'Ongera witoze kuri ibi bibazo.'}</h1><div class="results"><div class="result-card"><div class="score">${state.score}<small>/${state.quizSize}</small></div><h2>${passed ? 'Watsinze iki gice.' : 'Subiramo iki gice.'}</h2><p>${passed ? 'Komeza ku gice gikurikira cyangwa usubiremo ibisubizo.' : 'Nta kibazo. Subiramo ibi bibazo 20 mbere yo gukomeza.'}</p>${batchNote ? `<p class="batch-note">${batchNote}</p>` : ''}<div class="result-actions"><button class="secondary" onclick="retryQuiz()">Subiramo ibi bibazo 20</button>${nextBatchButton}</div><button class="secondary" onclick="go('home')">Ahabanza</button></div><div><div class="section-head"><h2>Ibyo wasubiramo</h2></div><div class="review-list">${state.missed.length ? state.missed.slice(0, 5).map((q) => `<div class="review-item"><p>${escapeHtml(q.question)}</p><small>Subiramo</small></div>`).join('') : '<div class="empty">Nta kibazo wibeshyeho. Ni byiza cyane!</div>'}</div></div></div>`; }
function renderTopics() { return `<div class="eyebrow">Amasomo</div><h1 style="font:700 38px 'Space Grotesk';margin:0 0 25px">Ingingo z’amategeko</h1><p class="topic-summary">Ibibazo ${sourceQuestions.length} byateguwe mu matsinda menshi. Ikibazo gishobora kuboneka mu ngingo zirenze imwe.</p><div class="topics-page">${categoryDefinitions.filter((category) => topicSets[category.key].length).map((category) => `<button class="topic-row" onclick="startTopic('${category.key}')"><div class="topic-icon">${category.icon}</div><div><b>${category.title}</b><p>${category.description}</p><span class="text-link">${topicSets[category.key].length} ibibazo · Hitamo iyi ngingo →</span></div></button>`).join('')}</div><button class="primary" style="margin-top:25px" onclick="startQuiz()">Gerageza ibibazo byose (${sourceQuestions.length}) →</button>`; }
function renderReview() { return `<div class="eyebrow">Isubiramo</div><h1 style="font:700 38px 'Space Grotesk';margin:0 0 25px">Wibande ku byo wibeshyeho.</h1>${state.missed.length ? `<div class="review-list">${state.missed.map((q) => `<div class="review-item"><p>${escapeHtml(q.question)}</p><small>Igisubizo: ${escapeHtml(q.options.find((o) => o.correct).text)}</small></div>`).join('')}</div>` : '<div class="empty">Nta bibazo byo gusubiramo ubu. Kora ikizamini kugira ngo utangire.</div>'}`; }
function renderLearningMaterials() { return `<section class="learning-materials"><div class="section-head"><div><div class="eyebrow">Kwiga birenze ikizamini</div><h2>Amashusho n’igitabo</h2></div><span class="materials-count">3 ibikoresho</span></div><div class="video-grid"><article class="video-card"><div class="video-frame"><iframe src="https://www.youtube-nocookie.com/embed/DR5g5e_86Ew" title="Isomo ry’amategeko y’umuhanda 1" loading="lazy" referrerpolicy="strict-origin-when-cross-origin" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe></div><h3>Isomo ry’amategeko y’umuhanda 1</h3><p>Reba iri somo mbere yo gukora ibibazo.</p><a class="video-link" href="https://www.youtube.com/watch?v=DR5g5e_86Ew" target="_blank" rel="noopener noreferrer">Fungura kuri YouTube →</a></article><article class="video-card"><div class="video-frame"><iframe src="https://www.youtube-nocookie.com/embed/fmWC5Bhg5AI" title="Isomo ry’amategeko y’umuhanda 2" loading="lazy" referrerpolicy="strict-origin-when-cross-origin" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe></div><h3>Isomo ry’amategeko y’umuhanda 2</h3><p>Ongera ubumenyi bwawe ukoresheje iri somo.</p><a class="video-link" href="https://www.youtube.com/watch?v=fmWC5Bhg5AI" target="_blank" rel="noopener noreferrer">Fungura kuri YouTube →</a></article><article class="pdf-card"><div class="pdf-preview"><iframe src="Amategeko%20y%27umuhanda%20%281%29.pdf#page=1" title="Amategeko y'umuhanda PDF" loading="lazy"></iframe></div><h3>Amategeko y’umuhanda</h3><p>Soma igitabo cyuzuye cy’amategeko n’ibibazo.</p><a class="video-link" href="Amategeko%20y%27umuhanda%20%281%29.pdf" target="_blank" rel="noopener noreferrer">Fungura PDF yose →</a></article></div></section>`; }
function renderPdfShortcut() { return '<a class="pdf-shortcut" href="Amategeko%20y%27umuhanda%20%281%29.pdf" target="_blank" rel="noopener noreferrer"><span>▤</span><span><strong>Soma Amategeko y’umuhanda</strong><small>Fungura PDF yose →</small></span></a>'; }
function go(view) { state.view = view; if (view !== 'quiz') state.answered = false; render(); }
function render() { document.querySelectorAll('.nav-link').forEach((link) => link.classList.toggle('active', link.dataset.view === state.view)); app.innerHTML = state.view === 'home' ? renderHome() : state.view === 'quiz' ? renderQuiz() : state.view === 'topics' ? renderTopics() : renderReview(); if (state.view === 'home') { app.insertAdjacentHTML('afterbegin', renderPdfShortcut()); app.insertAdjacentHTML('beforeend', renderLearningMaterials()); } }
window.startQuiz = startQuiz; window.startTopic = startTopic; window.startCategory = startCategory; window.nextCategoryBatch = nextCategoryBatch; window.retryQuiz = retryQuiz; window.chooseAnswer = chooseAnswer; window.checkAnswer = checkAnswer; window.nextQuestion = nextQuestion; window.go = go;
window.addEventListener('hashchange', () => { const view = location.hash.slice(1) || 'home'; if (view !== 'quiz') go(view); });
document.querySelectorAll('[data-view]').forEach((link) => link.addEventListener('click', () => go(link.dataset.view)));
const originalNext = nextQuestion;
function finishTracking() { state.attempts += 1; state.best = Math.max(state.best, Math.round(state.score / state.quizSize * 100)); localStorage.setItem('umuhandaAttempts', state.attempts); localStorage.setItem('umuhandaBest', state.best); }
const originalRender = render;
render = function() { if (state.view === 'quiz' && state.current === state.quizSize && !state.tracked) { state.tracked = true; finishTracking(); } if (state.view !== 'quiz') state.tracked = false; originalRender(); };
render();
